[package]
name = "freakstone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["macros"] }
tokio-macros = "2.3.0"
yew = {version = "0.21.0", features = ["csr"]}
